### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by saundemanu** [wolfinabox/Steelseries-OLED-Display-Mirror#1]
Could see a lot more downloads and usage with a ready-to-use release available.

**Comment by wolfinabox** [comment]
> 
> 
> Could see a lot more downloads and usage with a ready-to-use release available.

Thanks for the comment, this was more intended as a one off test type thing, but since a few people seem interested, I've put together a small GUI for it, and compiled a [release](https://github.com/wolfinabox/Steelseries-OLED-Display-Mirror/releases).
